"""portal query indexes

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 16:28:23.546809
"""
from __future__ import annotations

from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulation_summary', schema=None) as batch_op:
        batch_op.create_index('ix_regulation_summary_current', ['regulation_id', 'is_current'], unique=False)

    with op.batch_alter_table('unit_suggestion', schema=None) as batch_op:
        batch_op.create_index('ix_unit_suggestion_unit_active', ['unit_code', 'is_active', 'regulation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_suggestion', schema=None) as batch_op:
        batch_op.drop_index('ix_unit_suggestion_unit_active')

    with op.batch_alter_table('regulation_summary', schema=None) as batch_op:
        batch_op.drop_index('ix_regulation_summary_current')

    # ### end Alembic commands ###
