"""ilk şema: İK-1..İK-8 tabloları

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 16:22:54.070109
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_source_code'), ['source_code'], unique=False)

    op.create_table('app_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_event_type'), ['event_type'], unique=False)

    op.create_table('source',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('unit',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('regulatory_areas', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_doc_ref', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('fetch_run',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items_listed', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_changed', sa.Integer(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('structure_alert', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_code'], ['source.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetch_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetch_run_source_code'), ['source_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_run_started_at'), ['started_at'], unique=False)

    op.create_table('regulation',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('issuer', sa.String(length=64), nullable=True),
    sa.Column('issuer_name', sa.String(length=300), nullable=True),
    sa.Column('reg_type', sa.String(length=64), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('primary_source_code', sa.String(length=32), nullable=False),
    sa.Column('canonical_key', sa.String(length=600), nullable=False),
    sa.Column('processing_status', sa.String(length=24), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decided_by_title', sa.String(length=200), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('needs_dedupe_review', sa.Boolean(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('confidence_band', sa.String(length=8), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=True),
    sa.Column('severity_rationale', sa.Text(), nullable=True),
    sa.Column('ai_reg_type', sa.String(length=64), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('effective_date_text', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['primary_source_code'], ['source.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulation_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_is_relevant'), ['is_relevant'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_issuer'), ['issuer'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_severity'), ['severity'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=8), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('actor_title', sa.String(length=200), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_regulation_id'), ['regulation_id'], unique=False)

    op.create_table('fewshot_example',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fewshot_example', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fewshot_example_task'), ['task'], unique=False)

    op.create_table('llm_call',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_regulation_id'), ['regulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_task'), ['task'], unique=False)

    op.create_table('raw_document',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('listing_hash', sa.String(length=40), nullable=True),
    sa.Column('version_key', sa.String(length=200), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('fetch_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.String(length=24), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=24), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extract_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['fetch_run.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['raw_document.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.ForeignKeyConstraint(['source_code'], ['source.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'external_id', 'version', name='uq_raw_doc_version')
    )
    with op.batch_alter_table('raw_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_document_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_document_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_document_is_latest'), ['is_latest'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_document_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_document_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_document_regulation_id'), ['regulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_document_source_code'), ['source_code'], unique=False)

    op.create_table('regulation_summary',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('short_content', sa.Text(), nullable=False),
    sa.Column('short_content_evidence', sa.JSON(), nullable=False),
    sa.Column('relevant_topics', sa.JSON(), nullable=False),
    sa.Column('effective_date_evidence', sa.JSON(), nullable=True),
    sa.Column('grounding_score', sa.Float(), nullable=False),
    sa.Column('unverified_claims', sa.JSON(), nullable=False),
    sa.Column('source_links', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('llm_call_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulation_id', 'version', name='uq_summary_version')
    )
    with op.batch_alter_table('regulation_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulation_summary_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_summary_regulation_id'), ['regulation_id'], unique=False)

    op.create_table('manual_detection',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=True),
    sa.Column('unit_codes', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.String(length=200), nullable=True),
    sa.Column('matched_regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('matched_raw_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('match_method', sa.String(length=24), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_raw_document_id'], ['raw_document.id'], ),
    sa.ForeignKeyConstraint(['matched_regulation_id'], ['regulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_detection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_detection_matched_regulation_id'), ['matched_regulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_detection_publish_date'), ['publish_date'], unique=False)

    op.create_table('regulation_key',
    sa.Column('key', sa.String(length=600), nullable=False),
    sa.Column('regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('strong', sa.Boolean(), nullable=False),
    sa.Column('raw_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_document.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('regulation_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulation_key_regulation_id'), ['regulation_id'], unique=False)

    op.create_table('regulation_source_link',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('raw_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('match_method', sa.String(length=24), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_key', sa.String(length=600), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_document.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_document_id')
    )
    with op.batch_alter_table('regulation_source_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulation_source_link_regulation_id'), ['regulation_id'], unique=False)

    op.create_table('unit_suggestion',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('regulation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('unit_code', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('matched_responsibility', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('llm_call_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.ForeignKeyConstraint(['unit_code'], ['unit.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_suggestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_suggestion_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_suggestion_regulation_id'), ['regulation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_suggestion_regulation_id'))
        batch_op.drop_index(batch_op.f('ix_unit_suggestion_is_active'))

    op.drop_table('unit_suggestion')
    with op.batch_alter_table('regulation_source_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulation_source_link_regulation_id'))

    op.drop_table('regulation_source_link')
    with op.batch_alter_table('regulation_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulation_key_regulation_id'))

    op.drop_table('regulation_key')
    with op.batch_alter_table('manual_detection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_detection_publish_date'))
        batch_op.drop_index(batch_op.f('ix_manual_detection_matched_regulation_id'))

    op.drop_table('manual_detection')
    with op.batch_alter_table('regulation_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulation_summary_regulation_id'))
        batch_op.drop_index(batch_op.f('ix_regulation_summary_is_current'))

    op.drop_table('regulation_summary')
    with op.batch_alter_table('raw_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_document_source_code'))
        batch_op.drop_index(batch_op.f('ix_raw_document_regulation_id'))
        batch_op.drop_index(batch_op.f('ix_raw_document_published_at'))
        batch_op.drop_index(batch_op.f('ix_raw_document_processing_status'))
        batch_op.drop_index(batch_op.f('ix_raw_document_is_latest'))
        batch_op.drop_index(batch_op.f('ix_raw_document_external_id'))
        batch_op.drop_index(batch_op.f('ix_raw_document_content_sha256'))

    op.drop_table('raw_document')
    with op.batch_alter_table('llm_call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_task'))
        batch_op.drop_index(batch_op.f('ix_llm_call_regulation_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_input_hash'))

    op.drop_table('llm_call')
    with op.batch_alter_table('fewshot_example', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fewshot_example_task'))

    op.drop_table('fewshot_example')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_regulation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_created_at'))

    op.drop_table('audit_event')
    with op.batch_alter_table('regulation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulation_severity'))
        batch_op.drop_index(batch_op.f('ix_regulation_review_status'))
        batch_op.drop_index(batch_op.f('ix_regulation_publish_date'))
        batch_op.drop_index(batch_op.f('ix_regulation_processing_status'))
        batch_op.drop_index(batch_op.f('ix_regulation_issuer'))
        batch_op.drop_index(batch_op.f('ix_regulation_is_relevant'))
        batch_op.drop_index(batch_op.f('ix_regulation_effective_date'))
        batch_op.drop_index(batch_op.f('ix_regulation_detected_at'))

    op.drop_table('regulation')
    with op.batch_alter_table('fetch_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_run_started_at'))
        batch_op.drop_index(batch_op.f('ix_fetch_run_source_code'))

    op.drop_table('fetch_run')
    op.drop_table('unit')
    op.drop_table('source')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_event_type'))

    op.drop_table('outbox')
    op.drop_table('app_setting')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_source_code'))
        batch_op.drop_index(batch_op.f('ix_alert_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_alert_opened_at'))
        batch_op.drop_index(batch_op.f('ix_alert_key'))

    op.drop_table('alert')
    # ### end Alembic commands ###
