"""audit hash chain

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 16:23:38.231022
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('row_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_column('row_hash')
        batch_op.drop_column('prev_hash')

    # ### end Alembic commands ###
